// swift-tools-version: 5.9
// Auto-generated by the release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "PixellotPlayerSDK",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "PixellotPlayerSDK", targets: ["PixellotPlayerSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "PixellotPlayerSDK",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/PixellotPlayerSDK.xcframework.zip",
            checksum: "4f5737ec441013cd43bef5e4477e9d1c6cf7206fb4010bd3bb4851c7a961d2f8"
        ),
        .binaryTarget(
            name: "NpawPlugin",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/NpawPlugin.xcframework.zip",
            checksum: "2f8916eb099c78c2f05fd6b214675b8656029851eef76230dfb86506ea5f5216"
        ),
        .binaryTarget(
            name: "GCDWebServers",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/GCDWebServers.xcframework.zip",
            checksum: "c49284280904019ec91cbf364100bac0bba35f7659920f092a23332ff27fb3d5"
        ),
    ]
)
