// swift-tools-version: 5.9
// Auto-generated by the release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "PixellotPlayerSDK",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "PixellotPlayerSDK", targets: ["PixellotPlayerSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "PixellotPlayerSDK",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/PixellotPlayerSDK.xcframework.zip",
            checksum: "7d84cbabebf36969e09654507d1b79ae25ac0f395ab557aa3632c6fddbfb2bb6"
        ),
        .binaryTarget(
            name: "NpawPlugin",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/NpawPlugin.xcframework.zip",
            checksum: "e4c49000d7641d2f245977eaef22b951a25a79279f4d1998fae067f8f819af97"
        ),
        .binaryTarget(
            name: "GCDWebServers",
            url: "https://trialmmc5cr.jfrog.io/artifactory/pixellot-ios-local/PixellotPlayerSDK/0.0.1-test/GCDWebServers.xcframework.zip",
            checksum: "68639fee86fdacf23c1579d2ec1f6d7d2b27cdea41d882d8766911aed8749558"
        ),
    ]
)
