// swift-tools-version: 5.9
// Auto-generated by the release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "PixellotPlayerSDK",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "PixellotPlayerSDK", targets: ["PixellotPlayerSDK"]),
    ],
    targets: [
        .binaryTarget(
            name: "PixellotPlayerSDK",
            url: "https://github.com/Pixellot/player-sdk-spm/releases/download/ios-player%401.0.3/PixellotPlayerSDK.xcframework.zip",
            checksum: "98c36271efefc4b88fbce542e10d357853e50f20220d1d61ee9243aa5669bf10"
        ),
        .binaryTarget(
            name: "NpawPlugin",
            url: "https://github.com/Pixellot/player-sdk-spm/releases/download/ios-player%401.0.3/NpawPlugin.xcframework.zip",
            checksum: "dbd6349ad7070364c5f0791b063a27e7402c522d281a34d3b6947570cf04739c"
        ),
        .binaryTarget(
            name: "GCDWebServers",
            url: "https://github.com/Pixellot/player-sdk-spm/releases/download/ios-player%401.0.3/GCDWebServers.xcframework.zip",
            checksum: "4f29b783ef5a11d9969000240b2c1dbe854c04276e4bcd353328ffcbca61a1d8"
        ),
    ]
)
