# Auto-generated by the release pipeline — do not edit manually.
Pod::Spec.new do |s|
  s.name             = 'PixellotPlayerSDK'
  s.version          = '0.0.1-test'
  s.summary          = 'A pre-built video player SDK for iOS applications.'
  s.description      = 'Pre-built XCFramework distribution of the Pixellot video player SDK for iOS.'
  s.homepage         = 'https://github.com/Pixellot/player-sdk-spm'
  s.license          = { :type => 'EULA', :file => 'LICENSE' }
  s.author           = { 'Pixellot LTD' => 'sdk@pixellot.tv' }
  s.source           = { :http => 'https://trialmmc5cr.jfrog.io/artifactory/pixellot-cocoapods-local/PixellotPlayerSDK/0.0.1-test/PixellotPlayerSDK-0.0.1-test.zip', :sha256 => 'a424271ae2a7dff313285c6bced8267aa8aa1991cf4ebc1ab6f7e9113dd4a76a' }

  s.ios.deployment_target = '13.0'
  s.swift_version = '5.9'
  s.static_framework = true

  s.vendored_frameworks = 'PixellotPlayerSDK.xcframework',
                          'NpawPlugin.xcframework',
                          'GCDWebServers.xcframework'

  s.user_target_xcconfig = { 'ENABLE_USER_SCRIPT_SANDBOXING' => 'NO' }
end
